# Generated by Django 6.0.2 on 2026-02-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='precio',
            field=models.IntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$')], null=True),
        ),
    ]
