# Generated by Django 6.0.2 on 2026-03-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_sala_latitud_sala_longitud_alter_sala_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
